name: evaluacion_02
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  firebase_database: ^11.2.0
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
